# Generated by Django 5.0.6 on 2024-05-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmentregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetailsmodel',
            name='tracking_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
