# Generated by Django 5.0.6 on 2024-05-16 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDetailsModel',
            fields=[
                ('tracking_number', models.IntegerField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('expected_delivery_date', models.DateField(default=datetime.date.today)),
                ('mode_of_transport', models.CharField(choices=[('B', 'Bike'), ('C', 'Car'), ('D', 'Drone'), ('S', 'Starship robot'), ('T', 'Truck'), ('V', 'Van')], default='B', max_length=1)),
            ],
        ),
    ]
