# Generated by Django 5.0.6 on 2024-05-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmentregister', '0002_alter_shipmentdetailsmodel_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetailsmodel',
            name='mode_of_transport',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car'), ('Drone', 'Drone'), ('Starship robot', 'Starship robot'), ('Truck', 'Truck'), ('Van', 'Van')], default='B', max_length=20),
        ),
    ]
